apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: order-system
type: Opaque
stringData:
  DB_USER: eventuser
  DB_PASSWORD: eventpass
  DB_NAME: eventstore
  JWT_SECRET: super-secret-demo-key-change-in-real-prod
